hotels:
  dblist:
    - wingsent5:
        jdbc_driverClassName:
        jdbc_url:
        jdbc_user:
        jdbc_password:
    - wingsent3:
        jdbc_driverClassName:
        jdbc_url:
        jdbc_user:
        jdbc_password: